### ISSUE TITLE
AI Hub 성능 문의

### ISSUE THREAD

**Issue by heeyong-park** [park-cheol/ASR-Conformer#1]
안녕하세요 좋은 project 공유해 주셔서 감사합니다.
혹시 AI Hub 데이터 셋에서 성능이 얼마나 나왔는지 알 수 있을까요?

**Comment by PoKoHA** [comment]
답변이 늦어서 죄송합니다. 사정 상 Naver ClovaCall Dataset으로만 학습하여 AI Hub는 잘 모르겠습니다. ClovalCall 경우 CER: 약23% 였던 걸로 기억합니다.
